# Generated by Django 5.1 on 2024-08-17 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cuatrimestre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInhabilitacion',
            fields=[
                ('id_tipo_inhabilitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.tipoestado')),
            ],
        ),
        migrations.CreateModel(
            name='Inhabilitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_tipo_inhabilitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.tipoinhabilitacion')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offrc', models.IntegerField()),
                ('atendnc', models.IntegerField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.materia')),
            ],
            options={
                'unique_together': {('id_materia', 'id_alumno')},
            },
        ),
    ]
