# Generated by Django 5.1 on 2024-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoinhabilitacion",
            name="id_tipo_inhabilitacion",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
