# Generated by Django 5.1 on 2024-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_anio_ingreso_alumno_apellido_alumno_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cuil',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
