# Generated by Django 5.1 on 2024-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
