# Generated by Django 5.1 on 2024-08-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_alumno_celular_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(max_length=6),
        ),
    ]
