# Generated by Django 5.1 on 2024-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_alumno_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
