# Generated by Django 5.1 on 2024-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_alumno_celular_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
