# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Update npm packages weekly
  - package-ecosystem: "npm"
    directory: "/FrontAdmin"  # Assuming JavaScript files are in this directory (adjust as needed)
    schedule:
      interval: "weekly"

  # Update Python packages weekly
  - package-ecosystem: "pip"  # Update Python packages using pip
    directory: "/"       # Assuming Python files are in this directory (adjust as needed)
    schedule:
      interval: "weekly"

  # Update Ruby gems weekly (adjust "bundler" if using a different package manager)
  # - package-ecosystem: "bundler"  # Update Ruby gems using Bundler
  #   directory: "/ruby"          # Assuming Ruby files are in this directory (adjust as needed)
  #   schedule:
  #     interval: "weekly"

  # Configure additional package ecosystems as needed (e.g., Maven, Cargo)
  # - package-ecosystem: "..."  # Replace "..." with the appropriate ecosystem
  #   directory: "..."           # Specify the directory containing package manifests
  #   schedule:
  #     interval: "weekly"      # Adjust schedule as needed (e.g., "daily", "monthly")
