services:
  back: # Replace with your actual application name
    build: . # Build the backend service
    volumes:
      - .:/app/code # Mount current directory to /app/code in container
    ports:
      - "8000:8000" # Expose port 8000
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.dev
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
  db:
    image: mysql:8.0 # Use official MySQL image (adjust version if needed)
    environment:
      MYSQL_ROOT_PASSWORD: "1234" # Set a strong root password
      MYSQL_DATABASE: gestiontup # Define your database name
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for database data

volumes:
  mysql-data: {} # Define named volume for persistent MySQL data
