version: "3.8" # Adjust if needed based on your Docker Compose version

services:
  back: # Replace with your actual application name
    build: .
    volumes:
      - vol:/app/mnt/my-bucket/ # Adjust the volume name if needed
    ports:
      - "8000:8000" # Expose port 8000
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.base
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

volumes:
  vol: {} # Define an empty named volume
