# Generated by Django 5.1 on 2024-08-28 03:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_sysacad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/excel_files"
                ),
                upload_to="excel_files/",
            ),
        ),
    ]
