# Generated by Django 5.1 on 2024-08-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("excel_sysacad", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExcelFile",
        ),
    ]
