# Generated by Django 5.1 on 2024-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("excel_sysacad", "0002_delete_excelfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                ("id_excel", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="excel_files/")),
                ("fecha_subido", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Excel File",
                "verbose_name_plural": "Excel Files",
                "db_table": "excel_file",
            },
        ),
    ]
