# Generated by Django 5.1 on 2024-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('anio_cursada', models.PositiveSmallIntegerField()),
                ('anio_plan', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('cuatrimestre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('offrc', models.IntegerField()),
                ('atendnc', models.IntegerField()),
            ],
        ),
    ]
