# Generated by Django 5.1 on 2024-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anio_plan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo_materia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
