# Generated by Django 5.1 on 2024-09-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaalumno',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='materiaalumno',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaalumno',
            unique_together={('id_materia', 'id_alumno', 'anio')},
        ),
    ]
