# Generated by Django 5.1 on 2024-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_anio_plan_materia_codigo_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anio_cursada',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='anio_plan',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
