# Generated by Django 5.1 on 2024-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0003_remove_alumno_id_alter_alumno_dni_and_more"),
        ("materias", "0003_materia_anio_cursada_alter_materia_anio_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia",
            name="id_materia",
        ),
        migrations.AlterUniqueTogether(
            name="materiaalumno",
            unique_together={("id_materia", "id_alumno", "anio")},
        ),
        migrations.AddField(
            model_name="materiaalumno",
            name="anio",
            field=models.DateField(default=2024),
        ),
        migrations.AlterField(
            model_name="materia",
            name="codigo_materia",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="materiaalumno",
            name="atendnc",
        ),
        migrations.RemoveField(
            model_name="materiaalumno",
            name="offrc",
        ),
    ]
