# Generated by Django 5.1 on 2024-09-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericuser',
            table='Usuario',
        ),
    ]
