# Generated by Django 5.0.6 on 2024-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoDePago',
            fields=[
                ('id_comp_pago', models.AutoField(primary_key=True, serialize=False)),
                ('perfciclo', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('firmado', models.BooleanField()),
                ('fecha_firmado', models.DateTimeField()),
                ('compromiso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuota', models.IntegerField()),
                ('recargo', models.FloatField()),
                ('monto', models.FloatField()),
                ('firmado', models.BooleanField()),
                ('vencimiento', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago_devengado', models.DateField()),
                ('fecha_pedido', models.DateField()),
                ('tipo_puesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inhabilitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cuatrimestre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offrc', models.IntegerField()),
                ('atendnc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('medio_pago', models.CharField(max_length=255)),
                ('nro_recibo', models.IntegerField()),
                ('monto', models.FloatField()),
                ('estado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInhabilitacion',
            fields=[
                ('id_tipo_inhabilitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
