# Generated by Django 5.0.6 on 2024-07-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminrol',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.administrador'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
        migrations.AddField(
            model_name='inhabilitacion',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
        migrations.AddField(
            model_name='materiaalumno',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
        migrations.AddField(
            model_name='materiaalumno',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia'),
        ),
        migrations.AddField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuota'),
        ),
        migrations.AddField(
            model_name='adminrol',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='id_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permisos'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoestado'),
        ),
        migrations.AddField(
            model_name='inhabilitacion',
            name='id_tipo_inhabilitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoinhabilitacion'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaalumno',
            unique_together={('id_materia', 'id_alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='adminrol',
            unique_together={('id_admin', 'id_rol')},
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('id_rol', 'id_permiso')},
        ),
    ]
