# Generated by Django 5.1 on 2024-08-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisodepago',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='compromisodepago',
            name='fecha_firmado',
        ),
        migrations.RemoveField(
            model_name='compromisodepago',
            name='firmado',
        ),
        migrations.CreateModel(
            name='FirmaCompPagoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firmado', models.DateTimeField()),
                ('firmado', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('compromiso_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compromisodepago')),
            ],
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='alumnos',
            field=models.ManyToManyField(through='core.FirmaCompPagoAlumno', to='core.alumno'),
        ),
    ]
