# Generated by Django 5.1 on 2024-08-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_compromisodepago_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisodepago',
            name='alumnos',
        ),
        migrations.CreateModel(
            name='LineaDePago',
            fields=[
                ('id_linea_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_aplicado', models.FloatField()),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
            ],
        ),
    ]
