# Generated by Django 5.1 on 2024-08-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_compromisodepago_alumnos_lineadepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='archivo_pdf',
            field=models.FileField(default=1, upload_to='compromisos/'),
            preserve_default=False,
        ),
    ]
