# Generated by Django 5.1 on 2024-08-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_destinatariomensaje_mensaje_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compromisodepago'),
        ),
    ]
