# Generated by Django 5.1 on 2024-08-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_monto_compromisodepago_cuota_reducida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisodepago',
            name='comprimiso_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
