# Generated by Django 5.1 on 2024-08-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_compromisodepago_comprimiso_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='monto',
            new_name='compdepago',
        ),
    ]
