# Generated by Django 5.1 on 2024-08-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cuota_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='monto',
        ),
    ]
