# Generated by Django 5.1 on 2024-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_firmado_cuota_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
