# Generated by Django 5.1 on 2024-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cuota_pagada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='pagada',
        ),
        migrations.AddField(
            model_name='cuota',
            name='estado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
