# Generated by Django 5.1 on 2024-08-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_cuota_pagada_cuota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='archivo_pdf',
            field=models.FileField(blank=True, upload_to='compromisos/'),
        ),
    ]
