# Generated by Django 5.1 on 2024-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_compromisodepago_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='compromisos/'),
        ),
    ]
