# Generated by Django 5.1 on 2024-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_excelfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='id',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='id_excel',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
