# Generated by Django 5.1 on 2024-08-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_excelfile_id_excelfile_id_excel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfile',
            old_name='uploaded_at',
            new_name='fecha_subido',
        ),
    ]
