# Generated by Django 5.1 on 2024-08-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_uploaded_at_excelfile_fecha_subido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='cuota_reducida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='cuota_reducida_2venc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='cuota_reducida_3venc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='matricula',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='monto_completo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='monto_completo_2venc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='monto_completo_3venc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='perfciclo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
