# Generated by Django 5.1 on 2024-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_compromisodepago_cuota_reducida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='compromiso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
