# Generated by Django 5.1 on 2024-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_compromisodepago_compromiso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromisodepago',
            old_name='compromiso',
            new_name='curatrimestre',
        ),
        migrations.RemoveField(
            model_name='compromisodepago',
            name='perfciclo',
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_carga_comp_pdf',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_compr',
            field=models.DateField(blank=True, null=True),
        ),
    ]
