# Generated by Django 5.1 on 2024-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisodepago',
            name='fecha_compr',
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_carga_comp_pdf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
