# Generated by Django 5.1 on 2024-09-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmacomppagoalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='firmacomppagoalumno',
            name='compromiso_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.compromisodepago'),
        ),
        migrations.AddField(
            model_name='lineadepago',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cuota'),
        ),
        migrations.AddField(
            model_name='lineadepago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago'),
        ),
    ]
