# Generated by Django 5.1 on 2024-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_compromisodepago_fecha_carga_comp_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_ultima_modif',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
