# Generated by Django 5.1 on 2024-08-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_compromisodepago_fecha_ultima_modif'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisodepago',
            name='anio',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_ultima_modif',
            field=models.DateTimeField(auto_now_add=True, max_length=10, null=True),
        ),
    ]
