# Generated by Django 5.1 on 2024-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_compromisodepago_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_ultima_modif',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
